### ISSUE TITLE
Settings : help details have <br> uninterpreted

### ISSUE THREAD

**Issue by Spheerys** [Gibbs/modx-html-beautify#1]
On the last 2.0.1, the details of each setting are not beautified because of <br> inside the text :)

**Comment by gibbs** [comment]
Sorry, I don't understand this;

> "details of each setting are not beautified because of inside the text" 

Could you show an example?

**Comment by Spheerys** [comment]
of course : https://screenshots.firefox.com/jWkDf9aPWfTfV3br/adalie.eu
The html is not interpreted

**Comment by gibbs** [comment]
Strange, this has always worked before. I'll get them removed.

**Comment by Spheerys** [comment]
maybe you should keep them to explain the options ! It's just a small bug, maybe one day you will understand why the html is not interpreted !

**Comment by Spheerys** [comment]
Uh ! The problem is not only with xhtmlbeautify, but all setting parameters !
I will search for a similar issue on MODX :)

**Comment by Spheerys** [comment]
For information : https://github.com/modxcms/revolution/issues/14437
