### ISSUE TITLE
Version 2.0.1 doesn't work

### ISSUE THREAD

**Issue by Spheerys** [Gibbs/modx-html-beautify#2]
Hi,

I have installed the very last version (thank you!!!!) but it is not working.
I have activate it on the setting but nothing change, my code is still unbeautified.

What could be wrong ?

**Comment by gibbs** [comment]
I have uploaded a new pre-release at https://github.com/Gibbs/modx-html-beautify/releases/download/v2.0.1/xhtmlbeautify-2.0.1-pl.transport.zip. 

There seems to be problems with the build scripts not exporting plugin events.

**Comment by Spheerys** [comment]
Yes it's working now !
thank !
